development:
  redis:
    host: 127.0.0.1
    port: 6379
  telegram:
    endpoint: 'https://api.telegram.org/bot'
    parseMode: 'HTML'
    newline: '%0A%0A'
    newline_without_space: '%0A'
  maharashtra:
    endpoint: 'https://cdn-api.co-vin.in/api/v2/appointment/sessions/public'
    thane:
      token: '1815056790:AAF95WAFu5q52rq2vMnfGEzVPrxS1XQmG3Y'
      chat_id: '@thane_vaccine_alerts'
      code: '392'
    bhiwandi:
      token: '1807732484:AAH4n3UL8gDfI5E2-UKIUQ6XL2sQ5ZO0Yl4'
      chat_id: '@bhiwandi_vaccine_alerts'
      pincode: '421302'

production:
  redis:
    host: 127.0.0.1
    port: 6379
  telegram:
    endpoint: 'https://api.telegram.org/bot'
    parseMode: 'HTML'
    newline: '%0A%0A'
    newline_without_space: '%0A'
  maharashtra:
    endpoint: 'https://cdn-api.co-vin.in/api/v2/appointment/sessions/public'
    thane:
      token: '1815056790:AAF95WAFu5q52rq2vMnfGEzVPrxS1XQmG3Y'
      chat_id: '@thane_vaccine_alerts'
      code: '392'
    bhiwandi:
      token: '1807732484:AAH4n3UL8gDfI5E2-UKIUQ6XL2sQ5ZO0Yl4'
      chat_id: '@bhiwandi_vaccine_alerts'
      pincode: '421302'

